version: '3.8'

services:
  backend:
    build: .
    image: camaracamara1234/akwaba-sebeko-api
    ports:
      - "8000:8000"
    volumes:
      - media_data:/app/backend_api/media
    env_file:
      - .env
    environment:
      # L'URI est construite avec les variables du fichier .env pour l'authentification
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
  media_data:
